INSERT INTO EMPLOYEER (EMPLOYEER_ID, EMPLOYEER_NAME, EMPLOYEER_AGE, EMPLOYEER_SALARY, EMPLOYEER_POSITION )
VALUES (1, 'EMPLOYEER 1', 25, 26000.50, 'FRONTEND DEVELOPER');

INSERT INTO EMPLOYEER (EMPLOYEER_ID, EMPLOYEER_NAME, EMPLOYEER_AGE, EMPLOYEER_SALARY, EMPLOYEER_POSITION )
VALUES (2, 'EMPLOYEER 2', 27, 28000.50, 'BACKEND DEVELOPER');

INSERT INTO EMPLOYEER (EMPLOYEER_ID, EMPLOYEER_NAME, EMPLOYEER_AGE, EMPLOYEER_SALARY, EMPLOYEER_POSITION )
VALUES (3, 'EMPLOYEER 3', 34, 35000.75, 'ORGANIC ANALYST');

INSERT INTO EMPLOYEER (EMPLOYEER_ID, EMPLOYEER_NAME, EMPLOYEER_AGE, EMPLOYEER_SALARY, EMPLOYEER_POSITION )
VALUES (4, 'EMPLOYEER 4', 30, 38000.50, 'FUNCTIONAL ANALYST');

INSERT INTO EMPLOYEER (EMPLOYEER_ID, EMPLOYEER_NAME, EMPLOYEER_AGE, EMPLOYEER_SALARY, EMPLOYEER_POSITION )
VALUES (5, 'EMPLOYEER 5', 52, 45000.50, 'PRODUCT OWNER');
