CREATE TABLE EMPLOYEER (
    EMPLOYEER_ID INT AUTO_INCREMENT  PRIMARY KEY,
    EMPLOYEER_NAME VARCHAR(150) NOT NULL,
    EMPLOYEER_AGE INT NOT NULL,
    EMPLOYEER_SALARY DOUBLE NOT NULL,
    EMPLOYEER_POSITION VARCHAR(50) NOT NULL
);
